from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from datetime import datetime
import os


def generate_pdf_report(

    output_path,

    dataset_type,

    rows,

    columns,

    missing,

    duplicates,

    insights

):

    os.makedirs(
        os.path.dirname(output_path),
        exist_ok=True
    )

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    elements = []

    # --------------------------------
    # Title
    # --------------------------------

    elements.append(

        Paragraph(

            "<b><font size=20>"
            "Excel Automation Suite Pro"
            "</font></b>",

            styles["Title"]

        )

    )

    elements.append(
        Spacer(1, 20)
    )

    # --------------------------------
    # Report Information
    # --------------------------------

    elements.append(

        Paragraph(

            f"<b>Generated :</b> "
            f"{datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",

            styles["BodyText"]

        )

    )

    elements.append(
        Spacer(1, 15)
    )

    # --------------------------------
    # Dataset Summary
    # --------------------------------

    elements.append(

        Paragraph(

            "<b>Dataset Summary</b>",

            styles["Heading2"]

        )

    )

    table_data = [

        ["Dataset Type", dataset_type],

        ["Rows", rows],

        ["Columns", columns],

        ["Missing Values", missing],

        ["Duplicate Rows", duplicates]

    ]

    table = Table(table_data)

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke)

        ])

    )

    elements.append(table)

    elements.append(
        Spacer(1, 20)
    )

    # --------------------------------
    # AI Insights
    # --------------------------------

    elements.append(

        Paragraph(

            "<b>AI Insights</b>",

            styles["Heading2"]

        )

    )

    for key, value in insights.items():

        elements.append(

            Paragraph(

                f"<b>{key}</b> : {value}",

                styles["BodyText"]

            )

        )

    elements.append(
        Spacer(1, 20)
    )

    # --------------------------------
    # Footer
    # --------------------------------

    elements.append(

        Paragraph(

            "<font size=10>"
            "Generated by Excel Automation Suite Pro"
            "</font>",

            styles["Italic"]

        )

    )

    doc.build(elements)